### ISSUE TITLE
Plugin is broken with the latest(1.17.1) release of Flow

### ISSUE THREAD

**Issue by Spirit532** [Jessuhh/discord-timestamps-flowlauncher-plugin#8]
Not entirely sure whether this is the fault of the plugin or something broken in Flow, but here's the info:

## Exception

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   Source: System.Private.CoreLib
   TargetAssembly: System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
   TargetModule: System.Private.CoreLib.dll
   TargetSite: Void ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at Flow.Launcher.Core.Plugin.NodePlugin.RequestAsync(JsonRPCRequestModel request, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\NodePlugin.cs:line 31
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195

Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   Source: Flow.Launcher.Core
   TargetAssembly: Flow.Launcher.Core, Version=1.17.1.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Flow.Launcher.Core.dll
   TargetSite: Boolean <QueryForPluginAsync>b__1(Flow.Launcher.Plugin.ActionContext)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: AppData\Local\FlowLauncher\app-1.17.1\Flow.Launcher.dll
* Timestamp: 02/06/2024 03:29:22
* Flow Launcher version: 1.17.1
* OS Version: 19045.3570
* IntPtr Length: 8
* x64: True
* Python Path: C:\Python39\pythonw.exe
* Node Path: AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
* CLR Version: 7.0.14
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.09037
   * v4 Full 4.8.09037
   * v4.0 Client 4.0.0.0

**Comment by Spirit532** [comment]
Solved with the latest Flow update.
